server:
  port: 8083
  servlet:
    context-path: /notification-service
api:
  base:
    url: /api/

spring:
  kafka:
    bootstrap-servers: localhost:9092
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:delivery.tracking05@gmail.com}
    password: ${EMAIL_PASSWORD:pkjz cmlh ryos myfw}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
