server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/api/deliveries/**
          filters:
            - AuthenticationFilter
