server:
  port: 8081

api:
  base:
    url: /api/

spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    show-sql: true
  liquibase:
    enabled: ${LIQUIBASE_ENABLE:true}
    change-log: classpath:db.changelog/db.changelog.yaml
    default-schema: user_service

  jwt-key: bohXE2OGuhrk1Z32679iS9opXXvwYr2/g1/jaWrfwBsLNBEf7/ztx0VngupILXUy3RwpdCHzU3Qh2WZUejlB98QVU6aRjN2iEarrTtzHtxIbnVL5ckxb7cWPaeZkASzt+Rud8FzixpznH3nfm1UXbehUWzytfb8srEBTOVWhjLg=



  datasource:
    url: jdbc:postgresql://localhost:5432/tracking_system
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: user_service

  docker:
    compose:
      enabled: true
      file: user-service/docker/docker-compose.yaml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

info:
  title: User Service API
  description: APIs for managing users
  version: 1.0.0
