server:
  port: 8081
  servlet:
    context-path: /delivery-service
api:
  base:
    url: /api/

spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
  liquibase:
    enabled: ${LIQUIBASE_ENABLE:true}
    change-log: classpath:db.changelog/db.changelog.yaml
    default-schema: delivery_service




  datasource:
    url: jdbc:postgresql://localhost:5432/tracking_system
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: delivery_service

  docker:
    compose:
      enabled: true
      file: delivery-service/docker/docker-compose.yaml