services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: tracking_system
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - tracking-system-data:/var/lib/postgresql/data
    networks:
      - tracking-network

#  spring-app:
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile
#    container_name: tracking-system-app
#    depends_on:
#      - postgres-db
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/tracking_system
#      SPRING_DATASOURCE_USERNAME: username
#      SPRING_DATASOURCE_PASSWORD: password
#    networks:
#      - tracking-network
volumes:
  tracking-system-data:
    driver: local

networks:
  tracking-network:
    driver: bridge